# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('niveau', models.IntegerField()),
                ('bonus', models.CharField(blank=True, max_length=2500)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='weapons.Tag')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='weapons.Weapon')),
            ],
        ),
    ]
