# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-12 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='quality',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
