# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0002_stuff_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='bonus',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuff',
            name='niveau',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuff',
            name='type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
