# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0004_auto_20180515_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='id_image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
