# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0005_stuff_id_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffs.Stuff')),
            ],
        ),
    ]
