# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0007_tag_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='stuff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='stuffs.Stuff'),
        ),
    ]
