# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-17 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0008_auto_20180516_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='bonus',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
