# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0009_auto_20180517_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='niveau',
            field=models.IntegerField(),
        ),
    ]
