# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffs', '0010_auto_20180519_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
